server:
  port: 1158
spring:
  application:
    name: ${HOSTNAME:@hertzbeat@}-collector
  profiles:
    active: prod
  mvc:
    static-path-pattern: /**
  jackson:
    default-property-inclusion: ALWAYS
  # need to disable spring boot mongodb auto config, or default mongodb connection tried and failed..
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

common:
  queue:
    # memory or kafka
    type: kafka
    # properties when queue type is kafka
    kafka:
      servers: 192.168.40.39:19092
      alert-topic: async-collect-data-debug
      alert-metric-topic: temp-alert-data
      persistent-storage-topic: persistent-storage-data
      real-time-memoryStorage-topic: memory-data

#刷新采集配置信息URL
refreshUrl: http://127.0.0.1:1157/api/collector/getConfig?collectorId=1